name: Create JIRA on issue
on:
  issues:
    types: [opened]
jobs:
  create_jira:
    name: Create JIRA on NPT Project 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Create JIRA 
        env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          set -x
          apt-get update && apt-get install jq
          echo $EVENT_CONTEXT | jq '.'
          pip install jira && pip install yq