name: Release compiler image and CLI Binaries
on:
  create:
    tags:
      - v*
jobs:
  release-compiler-image:
    name: Release compiler image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout github repository
        uses: actions/checkout@v2
      - name: Upload CLI Binaries - DarwinAMD64
        id: upload-cli-binaries-darwin-amd64
        uses: svenstaro/upload-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
        with:
          repo_token: ${{ secrets.GITHUBTOKEN }}
          file: ./testfile
          asset_name: nexus-darwin_amd64
          tag: ${{ github.ref }}